version: "3.1"

services:
  lxdui:
    build:
      context: .
    hostname: lxdui
    container_name: lxdui
    restart: unless-stopped
    ports:
      - 15151:15151
    volumes:
      - /var/snap/lxd/common/lxd/unix.socket:/var/snap/lxd/common/lxd/unix.socket
