name: lxdui
version: '2.0'
summary: Web UI for Linux containers based on LXD/LXC.
description: |
  LXDUI is a Python Flask application that leverages LXD's Python client library, pylxd (https://github.com/lxc/pylxd), for interacting with the LXD REST API. It allows for rapid provisioning and management of large number of containers from a web browser, and you can simultaneously create any number of containers, even from multiple images, in one step.
grade: stable
confinement: strict
base: core18

apps:
  lxdui:
    command: lxdui
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs:
      - lxd
      - network
      - network-bind
      - network-control
      - network-manager

  webapp:
    command: lxdui start
    daemon: simple
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs:
      - lxd
      - network
      - network-bind
      - network-control
      - network-manager

parts:
  lxdui:
    source: .
    plugin: python
    python-version: python3
